version: '3.8'

services:

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: dev
      DB_PASS: devpass
      DB_NAME: orders_db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"